// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2qtwWj5a-t1RJCgOcun6cO4dwZoiBwpg',
    appId: '1:527744918361:android:101047fd703242e2bce248',
    messagingSenderId: '527744918361',
    projectId: 'tandangi-e3020',
    storageBucket: 'tandangi-e3020.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq2srIESEyW9Hbg5q0ksKmehcGXTpyXXg',
    appId: '1:527744918361:ios:2b98eb60a6d1f9bebce248',
    messagingSenderId: '527744918361',
    projectId: 'tandangi-e3020',
    storageBucket: 'tandangi-e3020.firebasestorage.app',
    androidClientId: '527744918361-psct79sdtf04fflut9kqopsg9hf8o1pg.apps.googleusercontent.com',
    iosClientId: '527744918361-jm1021h67cjrucfod6p3607co2gva5a7.apps.googleusercontent.com',
    iosBundleId: 'com.zetto.tandangi',
  );
}
